### ISSUE TITLE
What about destructive (`!`) methods?

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#139] opened 2017-10-08 08:27 UTC
I have a feeling like I already asked it but I can't find my question.

For example:
```ruby
  1.upto(7) do |i|
    x = image.width * i / 8
    image = image.draw_line [255, 0, 255], x, 0, x, image.height - 1
    y = image.height * i / 8
    image = image.draw_line [255, 0, 255], 0, y, image.width - 1, y
  end
```
Instead of `image = image.draw_line` I would like to write `image.draw_line!`.

UPD: Specifically in this case If I only needed horizontal lines I would write smth like `1.upto(7).inject(image) do |i, image|` and then would not need the `image =` but I need a chain of two operations. Probably I can do `image.draw_line(...).draw_line(...)` but that's not a style I want to see here.

**Comment by jcupitt** [comment] 2017-10-08 09:18
Hello, the problem is that libvips does not really support destructive operations. Having immutable images makes a lot of the sharing and caching systems much, much simpler. I did experiment with a destructive `draw_line` at one point, but a small mistake could produce a segv, so it seemed too dangerous. 

The way to do this safely is to do `image.copy` to make a fresh image which you are sure is not being shared, then to do a series of destructive operations, then to return the modified image. You could use it from Ruby perhaps like:

```ruby
modified_image = start_image.destructive do |x|
    x.draw_line! 255, 10, 10, 100, 100
    x.draw_line! 255, 10, 110, 100, -100
end
```

Maybe with something magic in `draw_line!` so it only works inside a `destructive` block.

**Comment by Nakilon** [comment] 2017-10-08 09:44
I don't mind how libvips works under the hood. Think about it as a Ruby-specific feature.
Here is another example.

Let's say we have some procedure that covers image with some drawings:
```ruby
some_iterator do |i|
  args1, args2 = f(i)
  image = image.draw_line *args1
  image = image.draw_line *args2
end
```
Now I decided to apply this not to a single image but to image1, image2 and image3. So I have to do this:
```ruby
image1, image2, image3 = [image1, image2, image3].map do |image|
  some_iterator do |i|
    args1, args2 = f(i)
    image = image.draw_line *args1
    image = image.draw_line *args2
  end
  image
end
```
or this:
```ruby
images = [image1, image2, image3]
images.map! do |image|
  some_iterator do |i|
    args1, args2 = f(i)
    image = image.draw_line *args1
    image = image.draw_line *args2
  end
  image
end
```
But what if I don't want the `images` array? With destructive methods I could do:
```ruby
[image1, image2, image3].each do |image|
  some_iterator do |i|
    args1, args2 = f(i)
    image!.draw_line *args1
    image!.draw_line *args2
  end
end
```

**Comment by Nakilon** [comment] 2017-10-08 09:50
Maybe define the `Image#replace` method and then smth like:
```ruby
list_of_image_methods_that_return_another_image = %i{ draw_line draw_circle }
list_of_image_methods_that_return_another_image.each do |method|
  Image.define_method "#{method}!" do |*args|
    self.replace self.send method, *args
  end
end
```

**Comment by jcupitt** [comment] 2017-10-08 09:56
You could simply add `draw_line!`, but if you made even a small mistake your program would crash with a segmentation fault, or perhaps generate corrupt output with no warnings. 

I think the difficulty is how to add destructive operations in a safe way.

**Comment by jcupitt** [comment] 2017-10-08 11:08
Let's tag this as an exhancement and experiment with destructive operations in a branch.

**Comment by jcupitt** [comment] 2017-10-10 07:43
Here's a branch that adds destructive draw:

https://github.com/jcupitt/ruby-vips/tree/destructive-draw

You use it like this:

```ruby
require "vips"

a = Vips::Image.new_from_file "/home/john/pics/k2.jpg"

n_lines = 1000

a = a.destructive do |image|
    n_lines.times do |i|
        image.draw_line 255, 
            i * image.width.fdiv(n_lines), image.height,
            0, i * image.height.fdiv(n_lines)
    end
end

a.write_to_file "x.jpg"
```

So a set of draw operations must be wrapped in a `destructive` block. It seems to work, it's reasonably quick, and it runs in very little memory, compared to the previous version anyway.

What do you think? 

Obvious improvements:

1. You can easily get a crash or a corrupt image if you use draw outside the block, or if you use non-destructive operations inside the block. There should  be some kind of lock to switch the kind of operations which are allowed and to catch mistakes. 

2. We should add a `!` to the end of all destructive operations. We could have both `draw_line` and `draw_line!`, and enforce the rule that they must be used in the right context.

**Comment by jcupitt** [comment] 2017-10-10 07:51
Another solution would just be to abandon the draw operations. They are only really useful for drawing on float or complex images (for example), where most drawing packages fail. 

A better alternative might be a helper function around `svgload_buffer`. Perhaps something like:

```ruby
image = image.composite '<rect x="0" y="0" width="1" height="1" style="fill:red"/>', :over
```

To render the SVG as an overlay on the image. This would be easy to implement and would give a much better set of drawing operations. The libvips svg renderer has no problems doing very, very large images, so it should scale better too.

**Comment by Nakilon** [comment] 2017-10-10 10:26
> enforce the rule that they must be used in the right context

We can define the ! method as a wrapper that calls a method without ! inside a context.

**Comment by Nakilon** [comment] 2017-10-10 11:09
Barely understanding inner working of the gem my approach is this:

```ruby
require "vips"

require "delegate"
class ImageMutable < SimpleDelegator
  %i{ draw_line draw_circle }.each do |m|
    define_method "#{m}!" do |*args|
      __setobj__ self.send m, *args
      self
    end
  end
end

image = ImageMutable.new Vips::Image.new_from_file "ab.png"

image.draw_circle! 0, 100, 100, 100

image.write_to_file "ab_.png"
```
based on https://stackoverflow.com/a/9131654/322020

**Comment by jcupitt** [comment] 2020-09-22 20:41
I made another branch with a possible solution:

https://github.com/libvips/ruby-vips/tree/add-mutableimage

This adds a new image class called `MutableImage`. You use it like this:

```ruby
#!/usr/bin/ruby
  
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

image = image.mutate do |mutable|
  (0 ... 1).step(0.01) do |i|
    mutable.draw_line! 255, mutable.width * i, 0, 0, mutable.height * (1 - i)
  end
end

image.write_to_file ARGV[1]
```

The idea is that the `copy` happens in the `mutate` member, then the block runs with the `MutableImage` as a parameter, then the block result is the mutated image turned back into a regular image again. Performance is obviously fantastic compared to the regular `draw_line`.

You can use it to modify image metadata too, eg.:

```ruby
image = image.mutate do |mutable|
  image.get_fields.each do |field|
    mutable.remove! field if field != "ixcc-profile-data"
  end
end
```

There's `set!` and `set_type!` as well.

`call` checks that you only use `method!` inside a mutate block, and `set!` etc. is only defined on `MutableImage`. I've not updated the docs. It should print a warning if you use `set` on a regular `Image`, but it doesn't yet. The API is unchanged (so `draw_image` on a regular image still works).

Comments etc. very welcome!

**Comment by jcupitt** [comment] 2020-09-22 21:16
@lovell @kleisauke this feels like a possible solution to the metadata modification problem. JS would be very like Ruby. C++ and Python would be a little awkward without an equivalent of blocks, though maybe Python's `with` could be abused?

**Comment by Nakilon** [comment] 2020-09-23 09:37
Interesting. What will be if I call `draw_line` on `MutableImage`? Does it make any sense? If not then by invoking the block we kind of told the computer already that we want to do mutating things and we don't have to tell it again by adding the `!`. I mean, do we really need to add the `!` to methods called on MutableImage?

**Comment by jcupitt** [comment] 2020-09-23 11:43
You're right, it's the same idea, but the implementation is new -- the classes are split so it can check and enforce the rules about what operations you can call when. The rules are checked here:

https://github.com/libvips/ruby-vips/blob/add-mutableimage/lib/vips/operation.rb#L383

The old `y = x.draw_line` still works. This makes a copy of `x` before calling `draw_line`, then returns the new image to `y`, so it's a pure function. It checks that `x` a plain `Image` and not a `MutableImage`. You can use it anywhere.

The new addition, `x.draw_line!` only works on `MutableImage`, and therefore only works in a mutate block. It skips the copy, since it knows that `MutableImage` is already unique and unshared. It's not a function (since it modifies `x`), but the mutate block as a whole is a pure function.

I've put the metadata modifiers like `set!` into `MutableImage` too -- they are rather broken at the moment, since `set` does no checking that the image is unshared.

Another example:

```ruby
#!/usr/bin/ruby

require 'vips'

# load and stream into memory
image = Vips::Image.new_from_file(ARGV[0], access: :sequential).copy_memory()

starting = Process.clock_gettime(Process::CLOCK_MONOTONIC)

lines = image
(0 .. 1).step 0.01 do |i|
  lines = lines.draw_line 255, lines.width * i, 0, 0, lines.height * (1 - i)
end

ending = Process.clock_gettime(Process::CLOCK_MONOTONIC)
puts "non-destructive took #{ending - starting}s"

starting = Process.clock_gettime(Process::CLOCK_MONOTONIC)

lines = image
lines = lines.mutate do |x|
  (0 .. 1).step 0.01 do |i|
    x.draw_line! 255, x.width * i, 0, 0, x.height * (1 - i)
  end
end

ending = Process.clock_gettime(Process::CLOCK_MONOTONIC)
puts "mutate took #{ending - starting}s"

lines.write_to_file ARGV[1]
```

I see:

```
$ ./mutate.rb ~/pics/k2.jpg x.jpg
non-destructive took 0.5115553569994518s
mutate took 0.14628159700077958s
```

With a huge drop in memory use too, of course, since it saves making 100 copies of the image.

**Comment by jcupitt** [comment] 2020-09-27 11:31
OK, merged to master for 2.0.18.

**Closed by jcupitt** 2020-09-27 11:31 UTC
Labels: enhancement

**Comment by jcupitt** [comment] 2021-03-08 15:14
Pushed as 2.1 https://libvips.github.io/libvips/2021/03/08/ruby-vips-mutate.html

**Comment by kleisauke** [comment] 2021-03-29 12:46
This was just landed in NetVips with commit https://github.com/kleisauke/net-vips/commit/89f374947656cebca0240439bd9d55a94fb04074.

**Comment by jcupitt** [comment] 2021-03-29 13:07
Oh nice! And the syntax is even OK. Good job Kleis!
